var Xero = require('xero');
 
console.log('this is working');

var xero = new Xero('LXWNZMTOGBJKN9URNNUUBPLX5ARQAY', 'EVFUBNGJIYKRZCVN7LZZMZIYTBDLIT', 
`-----BEGIN CERTIFICATE-----
MIICtDCCAh2gAwIBAgIJAPQxbJ2r8bFMMA0GCSqGSIb3DQEBCwUAMHMxCzAJBgNV
BAYTAk5aMRMwEQYDVQQIDApXZWxsaW5ndG9uMRMwEQYDVQQHDApXZWxsaW5ndG9u
MRIwEAYDVQQKDAlSRFRlc3RBcHAxEjAQBgNVBAsMCVJEVGVzdEFwcDESMBAGA1UE
AwwJUkRUZXN0QXBwMB4XDTE1MDQxNDAyNDUwNVoXDTIwMDQxMjAyNDUwNVowczEL
MAkGA1UEBhMCTloxEzARBgNVBAgMCldlbGxpbmd0b24xEzARBgNVBAcMCldlbGxp
bmd0b24xEjAQBgNVBAoMCVJEVGVzdEFwcDESMBAGA1UECwwJUkRUZXN0QXBwMRIw
EAYDVQQDDAlSRFRlc3RBcHAwgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBALiC
PD0d+2e8D6ZvDfEXbhA/phIUv00nVJqfACAOM5c+DcNkDJyoHJcSjGkWygcinfI8
BcVBSyZNOwvSuzGC1N74A0KTP/TxuVHL6V9JoYLQshuVPz8TQsAbtjlLOUk/bNO0
IBVr+e1lKvsaYVy0V9qxb7/8t+bAaz3jUb8YCkTdAgMBAAGjUDBOMB0GA1UdDgQW
BBR/qnqcmx9bwJi5POH8l3A7eeSPPDAfBgNVHSMEGDAWgBR/qnqcmx9bwJi5POH8
l3A7eeSPPDAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBCwUAA4GBAJu1EuP47k5p
x9VdqcC/qGm2FEkpxtLfpnnMnK2rNc6h3sfzJR+kc88gkYJAfK1RPPgbPWPfCQHM
aBPtX5s2ccGZG0eUrgDpASRZM2w7uFfEclPp9lI+6Z/J4cq7sKK/ER5Uyf6sjTl5
+qNPghfXNB8yD5KeY2du2VHXELkisB6Y
-----END CERTIFICATE-----`);

xero.call('GET', '/Users', null, function(err, json) {
        if (err) {
            log.error(err);
            return res.json(400, {error: 'Unable to contact Xero'});
        }
        return res.json(200, json);
    });